Repository mongodb/snooty-parser, pull requests merged in 2019-10, with the labels that each got.

#40 Fix the spelling of PAT_EXPLICIT_TITLE
  snooty/rstparser.py
Labels: bug

#37 DOCSP-6175: creating test for merge conflict artifacts
  snooty/test_project.py
  snooty/test_util.py
  snooty/types.py
  test_data/merge_conflict/snooty.toml
  test_data/merge_conflict/source/index.txt
Labels: enhancement, good first issue

#22 DOCSP-6544: Add RPC method to return page AST
  RPC-methods.md
  snooty/language_server.py
  snooty/parser.py
  snooty/test_language_server.py
  snooty/test_util.py
  test_data/test_project_embedding_includes/snooty.toml
  test_data/test_project_embedding_includes/source/images/compass-create-database.png
  test_data/test_project_embedding_includes/source/includes/include_child.rst
  test_data/test_project_embedding_includes/source/includes/steps-migrate-compose-pr.yaml
  test_data/test_project_embedding_includes/source/includes/test_rst.rst
  test_data/test_project_embedding_includes/source/index.txt
Labels: enhancement

#51 bugfix: code block language is optional
  snooty/parser.py
  snooty/rstparser.py
  snooty/test_parser.py
Labels: bug
