Repository mongodb/snooty-parser, pull requests merged in 2020-12, with the labels that each got.

#262 Portability Improvements
  snooty/gizaparser/test_extracts.py
  snooty/gizaparser/test_release.py
  snooty/gizaparser/test_steps.py
  snooty/language_server.py
  snooty/main.py
  snooty/n.py
  snooty/parser.py
  snooty/rstparser.py
  snooty/test_language_server.py
  snooty/test_main.py
  snooty/test_util.py
  snooty/types.py
  snooty/util.py
Labels: enhancement

#271 DOP-1777: Update driver, compass, and ecosystem extlink roles
  snooty/rstspec.toml
Labels: rstspec change

#275 fix watchdog dependency with updating correct version number
  pyproject.toml
Labels: bug

#270 DOP-1584: manpage builder
  snooty/builders/__init__.py
  snooty/builders/man.py
  snooty/builders/test_man.py
  snooty/parser.py
  snooty/types.py
  snooty/util_test.py
  stubs/pytest.pyi
Labels: enhancement
