Repository mongodb/snooty-parser, pull requests merged in 2020-10, with the labels that each got.

#231 DOP-1586: Support targets with escaped angle brackets
  snooty/rstparser.py
  snooty/test_parser.py
  stubs/docutils/nodes.pyi
Labels: bug

#232 DOP-1589: Support required arguments
  snooty/rstparser.py
  snooty/rstspec.toml
  snooty/specparser.py
  snooty/test_parser.py
Labels: bug, enhancement

#233 Improve callable target handling
  snooty/rstparser.py
  snooty/test_parser.py
Labels: bug

#235 DOP-1450: define and formally support tabs in rstspec.toml
  snooty/diagnostics.py
  snooty/parser.py
  snooty/rstparser.py
  snooty/rstspec.toml
  snooty/specparser.py
  snooty/test_parser.py
  test_data/test_tabs.rst
Labels: enhancement

#234 DOP-1595: Correctly inherit YAML ref names
  snooty/gizaparser/nodes.py
  snooty/gizaparser/test_extracts.py
  snooty/gizaparser/test_steps.py
  test_data/steps-test-child.yaml
  test_data/steps-test-grandchild.yaml
Labels: bug

#230 DOP-1018: Preserve source fileid through includes
  snooty/eventparser.py
  snooty/gizaparser/extracts.py
  snooty/gizaparser/release.py
  snooty/gizaparser/steps.py
  snooty/gizaparser/test_extracts.py
  snooty/gizaparser/test_nodes.py
  snooty/gizaparser/test_release.py
  snooty/gizaparser/test_steps.py
  snooty/language_server.py
  snooty/n.py
  snooty/page.py
  snooty/parser.py
  snooty/postprocess.py
  snooty/test_language_server.py
  snooty/test_legacy_guides.py
  snooty/test_openapi.py
  snooty/test_parser.py
  snooty/test_postprocess.py
  snooty/test_postprocess_old_and_monolithic.py
  snooty/test_project.py
  snooty/test_util.py
  snooty/types.py
  test_data/test_gizaparser/snooty.toml
  test_data/test_gizaparser/source/includes/extracts-test-parent.yaml
  test_data/test_gizaparser/source/includes/extracts-test.yaml
  test_data/test_gizaparser/source/includes/release-base-repeat.yaml
  test_data/test_gizaparser/source/includes/release-base.yaml
  test_data/test_gizaparser/source/includes/release-specifications.yaml
  test_data/test_gizaparser/source/includes/steps-test-child.yaml
  test_data/test_gizaparser/source/includes/steps-test-grandchild.yaml
  test_data/test_gizaparser/source/includes/steps-test.yaml
Labels: bug
