Repository mongodb/snooty-parser, pull requests merged in 2021-05, with the labels that each got.

#309 DOP-1810: fix handling of pymongo, motor, and phplib links
  snooty/intersphinx.py
  snooty/rstspec.toml
Labels: bug

#310 Use the specified Python when creating a venv
  Makefile
Labels: enhancement

#311 DOP-2117: Add layout option to landing Cards
  snooty/rstspec.toml
  snooty/test_landing.py
  test_data/test_landing/source/index.txt
Labels: enhancement, rstspec change

#312 Upgrade GitHub Actions ubuntu runner to 20.04
  .github/workflows/test.yml
Labels: enhancement
