Repository mongodb/snooty-parser, pull requests merged in 2021-02, with the labels that each got.

#283 DOP-1816: Permit tarballing of manpages
  snooty/builders/test_man.py
  snooty/diagnostics.py
  snooty/parser.py
  snooty/types.py
Labels: enhancement

#289 Fix tarball members mode
  snooty/builders/test_man.py
  snooty/parser.py
Labels: bug

#288 Relax dependency constraints
  pyproject.toml
Labels: enhancement

#287 Don't crash on failed intersphinx fetch: raise diagnostic
  snooty/diagnostics.py
  snooty/parser.py
  snooty/target_database.py
  snooty/test_intersphinx.py
Labels: bug

#282 DOP-1896: Update OpenAPI directive to allow parsing through the frontend
  snooty/parser.py
  snooty/rstspec.toml
  snooty/test_openapi.py
Labels: breaking, enhancement

#293 Don't crash if invoked in a child directory of a project
  snooty/parser.py
  snooty/test_project.py
Labels: bug
