Repository mongodb/snooty-parser, pull requests merged in 2021-06, with the labels that each got.

#315 DOP-2196: Remove \x00 characters from text nodes
  snooty/parser.py
  snooty/test_parser.py
Labels: bug

#316 Optimize eventparser.py
  snooty/eventparser.py
Labels: enhancement

#314 DOP-2215: Domain overhaul + remove all guides content
  CHANGELOG.md
  snooty/legacy_guides.py
  snooty/parser.py
  snooty/rstparser.py
  snooty/rstspec.toml
  snooty/test_legacy_guides.py
  snooty/test_mongodb_domain.py
  snooty/test_parser.py
  snooty/test_util.py
  test_data/guides/test_guides.rst
  test_data/guides/test_legacy_guides.rst
  test_data/test_landing/snooty.toml
  test_data/test_mongodb_domain/snooty.toml
  test_data/test_mongodb_domain/source/images/pink.png
  test_data/test_mongodb_domain/source/index.txt
Labels: PLP, do not merge

#324 Error when loading an invalid rstspec link definition
  snooty/specparser.py
  snooty/test_specparser.py
Labels: enhancement

#326 DOP-2292: Correctly generate intersphinx inventory for targets on ind…
  snooty/n.py
  snooty/target_database.py
  snooty/test_intersphinx.py
Labels: bug
